// Copyright (c) All contributors. All rights reserved. Licensed under the MIT license.

namespace Arc.Unit;

/// <summary>
/// This is the base class of Product, generated by the Unit builder.<br/>
/// <b>Unit = Builder + Product(Instance) + Function</b>
/// </summary>
public class UnitProduct
{
    /// <summary>
    /// Initializes a new instance of the <see cref="UnitProduct"/> class.
    /// </summary>
    /// <param name="context"><see cref="UnitContext"/>.</param>
    public UnitProduct(UnitContext context)
    {
        this.Context = context;
    }

    public UnitContext Context { get; }
}
